[package]
name = "web5-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
jsonwebkey = "0.3.5"
leveldb-rs = "0.0.7"
regex = "1.10.4"
thiserror = "1.0.60"
varint-rs = "2.2.0"
